### ISSUE TITLE
求一款落格输入法X的脚本

### ISSUE THREAD

**Issue by xjwhust** [Alex0510/surge#7]
看到作者的kdsp的更新，太赞了，作者有时间看看这款落格输入法X，看有没有对应的脚本，十分感谢

**Comment by Alex0510** [comment]
已添加ng------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月22日(星期天) 晚上11:01
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [Alex0510/surge] 求一款落格输入法X的脚本 (#7)




 
看到作者的kdsp的更新，太赞了，作者有时间看看这款落格输入法X，看有没有对应的脚本，十分感谢
 
&mdash;

**Comment by Alex0510** [comment]
落格输入法x已经上传到ng.js

发自我的iPhone

**Comment by xjwhust** [comment]
> 落格输入法x已经上传到ng.js 发自我的iPhone
> […](#)
> 在 2020年3月22日，下午11:01，xjwhust ***@***.***> 写道： ﻿ 看到作者的kdsp的更新，太赞了，作者有时间看看这款落格输入法X，看有没有对应的脚本，十分感谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
凌晨就收到回复，感动与感谢，有个问题，输入法目前还不能解锁，作者有空的时候麻烦再修改一下

**Comment by Alex0510** [comment]
可以解锁Pro，已经测试了------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 上午9:11
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 求一款落格输入法X的脚本 (#7)




  
落格输入法x已经上传到ng.js 发自我的iPhone
 …
 在 2020年3月22日，下午11:01，xjwhust @.***> 写道： &#xFEFF; 看到作者的kdsp的更新，太赞了，作者有时间看看这款落格输入法X，看有没有对应的脚本，十分感谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 凌晨就收到回复，感动与感谢，有个问题，输入法目前还不能解锁，作者有空的时候麻烦再修改一下
  
&mdash;

**Comment by Alex0510** [comment]
------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 上午9:11
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 求一款落格输入法X的脚本 (#7)




  
落格输入法x已经上传到ng.js 发自我的iPhone
 …
 在 2020年3月22日，下午11:01，xjwhust @.***> 写道： &#xFEFF; 看到作者的kdsp的更新，太赞了，作者有时间看看这款落格输入法X，看有没有对应的脚本，十分感谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
 凌晨就收到回复，感动与感谢，有个问题，输入法目前还不能解锁，作者有空的时候麻烦再修改一下
  
&mdash;

**Comment by xjwhust** [comment]
自己太粗心了，没有及时刷新更新脚本，提的问题也不专业，已经可以啦，再次感谢

**Comment by iKangnir** [comment]
首先，大佬辛苦了。落格我远程本地都试了，恢复购买也试了，都不行啊，无法激活Pro。表达式和hostname我检查了也都没有错，不知道哪里出了问题。请大佬示下。

**Comment by iKangnir** [comment]
> 自己太粗心了，没有及时刷新更新脚本，提的问题也不专业，已经可以啦，再次感谢

前辈，为啥我的不行？远程本地都不好使，表达式和hostname检查也无误，就是无法激活Pro。请不吝赐教

**Comment by Alex0510** [comment]
都是正常的啊，添加脚本即可------------------ 原始邮件 ------------------
发件人: "iKangnir Cribug"<notifications@github.com>
发送时间: 2020年3月25日(星期三) 上午10:43
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] 求一款落格输入法X的脚本 (#7)




 
首先，大佬辛苦了。落格我远程本地都试了，恢复购买也试了，都不行啊，无法激活Pro。表达式和hostname我检查了也都没有错，不知道哪里出了问题。请大佬示下。
 
&mdash;

**Comment by iKangnir** [comment]
> 都是正常的啊，添加脚本即可------------------ 原始邮件 ------------------ 发件人: "iKangnir Cribug"<notifications@github.com> 发送时间: 2020年3月25日(星期三) 上午10:43 收件人: "Alex0510/surge"<surge@noreply.github.com>; 抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Alex0510/surge] 求一款落格输入法X的脚本 (#7) 首先，大佬辛苦了。落格我远程本地都试了，恢复购买也试了，都不行啊，无法激活Pro。表达式和hostname我检查了也都没有错，不知道哪里出了问题。请大佬示下。 &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我这不行，不知道是不是脚本有冲突？远程和本地我都试了，正则表达式和hostname我跟大佬的js描述也对比了，丝毫不差。但是，就是不能激活Pro。马卡龙那个一开始我以为不行，但等了一会儿就好了，落格的等了一上午，也没出来。不知道究竟是哪里出了问题。

**Comment by fangpidedongsun** [comment]
我的正常

**Comment by fangpidedongsun** [comment]
> > 都是正常的啊，添加脚本即可------------------ 原始邮件 ------------------ 发件人: "iKangnir Cribug"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2020年3月25日(星期三) 上午10:43 收件人: "Alex0510/surge"[surge@noreply.github.com](mailto:surge@noreply.github.com); 抄送: "Eric"[398201034@qq.com](mailto:398201034@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [Alex0510/surge] 求一款落格输入法X的脚本 (#7) 首先，大佬辛苦了。落格我远程本地都试了，恢复购买也试了，都不行啊，无法激活Pro。表达式和hostname我检查了也都没有错，不知道哪里出了问题。请大佬示下。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 我这不行，不知道是不是脚本有冲突？远程和本地我都试了，正则表达式和hostname我跟大佬的js描述也对比了，丝毫不差。但是，就是不能激活Pro。马卡龙那个一开始我以为不行，但等了一会儿就好了，落格的等了一上午，也没出来。不知道究竟是哪里出了问题。

你是不是还有其他的软件用到这个正则
http-response ^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt
如果有的话需要把这个放在前面，后面的就会失效。
