### ISSUE TITLE
speedtest脚本

### ISSUE THREAD

**Issue by xjwhust** [Alex0510/surge#9]
下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢

**Comment by Alex0510** [comment]
我测试了不行，恢复不成功

发自我的iPhone

**Comment by xjwhust** [comment]
> 我测试了不行，恢复不成功
> 
> 发自我的iPhone
> 
> > 在 2020年3月23日，下午2:31，xjwhust <notifications@github.com> 写道：
> > 
> > ﻿
> > 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 

好的，明白，感谢你的付出哈

**Comment by Alex0510** [comment]
我已经上传了，你试试吧

发自我的iPhone

**Comment by Alex0510** [comment]
帮忙测试一下新增的那几个APP------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月23日(星期一) 晚上10:18
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] speedtest脚本 (#9)




  
我测试了不行，恢复不成功
 
发自我的iPhone
  
在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道：
 
&#xFEFF;
 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢
 
—
 You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub, or unsubscribe.
   
好的，明白，感谢你的付出&#x54C8;
 
&mdash;

**Comment by xjwhust** [comment]
> 帮忙测试一下新增的那几个APP------------------ 原始邮件 ------------------ 发件人: "xjwhust"<notifications@github.com> 发送时间: 2020年3月23日(星期一) 晚上10:18 收件人: "Alex0510/surge"<surge@noreply.github.com>; 抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道： &#xFEFF; 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出&#x54C8; &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

好的，收到，测试完给你回复

**Comment by xjwhust** [comment]
> > 帮忙测试一下新增的那几个APP------------------ 原始邮件 ------------------ 发件人: "xjwhust"[notifications@github.com](mailto:notifications@github.com) 发送时间: 2020年3月23日(星期一) 晚上10:18 收件人: "Alex0510/surge"[surge@noreply.github.com](mailto:surge@noreply.github.com); 抄送: "Eric"[398201034@qq.com](mailto:398201034@qq.com);"Comment"[comment@noreply.github.com](mailto:comment@noreply.github.com); 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust [notifications@github.com](mailto:notifications@github.com) 写道： ﻿ 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出哈 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 好的，收到，测试完给你回复

speedtest恢复失败，instake可以内购，inscopy暂未测试（Instagram太久没用，停用一天），后面及时反馈给你哈

**Comment by Alex0510** [comment]
你用的是哪一个speedtext，我的是2.8版本那个------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月24日(星期二) 凌晨0:03
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] speedtest脚本 (#9)




   
帮忙测试一下新增的那几个APP------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "xjwhust"notifications@github.com 发送时间: 2020年3月23日(星期一) 晚上10:18 收&#x4EF6;人: "Alex0510/surge"surge@noreply.github.com; 抄送: "Eric"398201034@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道： &#xFEFF; 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出&#x54C8; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
好的，收到，测试完给你回复
  
speedtest恢复失败，instake可以内购，inscopy暂未测试（Instagram太久没用，停用一天），后面及时反馈给你&#x54C8;
 
&mdash;

**Comment by xjwhust** [comment]
这个呢，我们说的不是同一个，哈哈

--


&nbsp;祝好~
辛集武

华中科技大学材料学院
湖北省武汉市洪山区珞喻路1037号&nbsp;

------------------------




&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Eric"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月24日(星期二) 凌晨0:06
收件人:&nbsp;"Alex0510/surge"<surge@noreply.github.com&gt;;
抄送:&nbsp;"辛集武"<784253089@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Alex0510/surge] speedtest脚本 (#9)





 你用的是哪一个speedtext，我的是2.8版本那个------------------ 原始邮件 ------------------ 
 发件人: "xjwhust"<notifications@github.com&gt; 
 发送时间: 2020年3月24日(星期二) 凌晨0:03 
 收件人: "Alex0510/surge"<surge@noreply.github.com&gt;; 
 抄送: "Eric"<398201034@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 
 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 
 
 
 
 
     
 帮忙测试一下新增的那几个APP------------------ 原始邮&amp;#x4EF6; ------------------ 发&amp;#x4EF6;人: "xjwhust"notifications@github.com 发送时间: 2020年3月23日(星期一) 晚上10:18 收&amp;#x4EF6;人: "Alex0510/surge"surge@noreply.github.com; 抄送: "Eric"398201034@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道： &amp;#xFEFF; 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出&amp;#x54C8; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 
    
 好的，收到，测试完给你回复 
    
 speedtest恢复失败，instake可以内购，inscopy暂未测试（Instagram太久没用，停用一天），后面及时反馈给你&amp;#x54C8; 
   
 &amp;mdash;

**Comment by Alex0510** [comment]
speedtext太多了，不知道是哪个------------------ 原始邮件 ------------------
发件人: "xjwhust"<notifications@github.com>
发送时间: 2020年3月24日(星期二) 凌晨0:10
收件人: "Alex0510/surge"<surge@noreply.github.com>;
抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [Alex0510/surge] speedtest脚本 (#9)




 这个呢，我们说的不是同一个，&#x54C8;&#x54C8; 
 
 -- 
 
 
 &nbsp;祝好~ 
 辛集武 
 
 华中科技大学材料学院 
 &#x6E56;北省武汉市洪山区珞喻路1037号&nbsp; 
 
 ------------------------ 
 
 
 
 
 &nbsp; 
 
 
 
 
 
 ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 
 发&#x4EF6;人:&nbsp;"Eric"<notifications@github.com&gt;; 
 发送时间:&nbsp;2020年3月24日(星期&#x4E8C;) 凌晨0:06 
 收&#x4EF6;人:&nbsp;"Alex0510/surge"<surge@noreply.github.com&gt;; 
 抄送:&nbsp;"辛集武"<784253089@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 
 主题:&nbsp;Re: [Alex0510/surge] speedtest脚本 (#9) 
 
 
 
 
 
  你用的是哪一个speedtext，我的是2.8版本那个------------------ 原始邮&#x4EF6; ------------------  
  发&#x4EF6;人: "xjwhust"<notifications@github.com&gt;  
  发送时间: 2020年3月24日(星期&#x4E8C;) 凌晨0:03  
  收&#x4EF6;人: "Alex0510/surge"<surge@noreply.github.com&gt;;  
  抄送: "Eric"<398201034@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;  
  主题: Re: [Alex0510/surge] speedtest脚本 (#9)  
   
   
   
   
       
  帮忙测试一下新增的那几个APP------------------ 原始邮&amp;#x4EF6; ------------------ 发&amp;#x4EF6;人: "xjwhust"notifications@github.com 发送时间: 2020年3月23日(星期一) 晚上10:18 收&amp;#x4EF6;人: "Alex0510/surge"surge@noreply.github.com; 抄送: "Eric"398201034@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道： &amp;#xFEFF; 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出&amp;#x54C8; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.  
      
  好的，收到，测试完给你回复  
      
  speedtest恢复失败，instake可以内购，inscopy暂未测试（Instagram太久没用，停用一天），后面及时反馈给你&amp;#x54C8;  
     
  &amp;mdash;  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you authored the thread. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by xjwhust** [comment]
> speedtext太多了，不知道是哪个------------------ 原始邮件 ------------------ 发件人: "xjwhust"<notifications@github.com> 发送时间: 2020年3月24日(星期二) 凌晨0:10 收件人: "Alex0510/surge"<surge@noreply.github.com>; 抄送: "Eric"<398201034@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 这个呢，我们说的不是同一个，&#x54C8;&#x54C8;
> […](#)
> -- &nbsp;祝好~ 辛集武 华中科技大学材料学院 &#x6E56;北省武汉市洪山区珞喻路1037号&nbsp;
> ------------------------ &nbsp;
> ------------------&nbsp;原始邮&#x4EF6;&nbsp;------------------ 发&#x4EF6;人:&nbsp;"Eric"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月24日(星期&#x4E8C;) 凌晨0:06 收&#x4EF6;人:&nbsp;"Alex0510/surge"<surge@noreply.github.com&gt;; 抄送:&nbsp;"辛集武"<784253089@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [Alex0510/surge] speedtest脚本 (#9) 你用的是哪一个speedtext，我的是2.8版本那个------------------ 原始邮&#x4EF6; ------------------ 发&#x4EF6;人: "xjwhust"<notifications@github.com&gt; 发送时间: 2020年3月24日(星期&#x4E8C;) 凌晨0:03 收&#x4EF6;人: "Alex0510/surge"<surge@noreply.github.com&gt;; 抄送: "Eric"<398201034@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 帮忙测试一下新增的那几个APP------------------ 原始邮&amp;#x4EF6; ------------------ 发&amp;#x4EF6;人: "xjwhust"notifications@github.com 发送时间: 2020年3月23日(星期一) 晚上10:18 收&amp;#x4EF6;人: "Alex0510/surge"surge@noreply.github.com; 抄送: "Eric"398201034@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [Alex0510/surge] speedtest脚本 (#9) 我测试了不行，恢复不成功 发自我的iPhone 在 2020年3月23日，下午2:31，xjwhust notifications@github.com 写道： &amp;#xFEFF; 下午好~，speedtest（港区版本835095861，Ookla）是一款很优秀的测速APP，作者有时间的时候能否设计一下脚本，谢谢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，明白，感谢你的付出&amp;#x54C8; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 好的，收到，测试完给你回复 speedtest恢复失败，instake可以内购，inscopy暂未测试（Instagram太久没用，停用一天），后面及时反馈给你&amp;#x54C8; &amp;mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. &mdash; You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Ookla这个开发商的

**Comment by xjwhust** [comment]
Ookla开发商的

**Comment by xjwhust** [comment]
今早最新测试，inscopy和instake都么问题。

**Comment by xjwhust** [comment]
作者如果方便的话tg（Summeryiyi）一下我哈
